<simulationsScreen>:
    BoxLayout:
        orientation:'vertical'
        Label:
            text: 'Simulações'
            font_size: 50
        Button:
            text: 'Simulação 1'
            font_size: 30
            on_release:
        Button:
            text: 'Simulação 2'
            font_size: 30
            on_release:
        Button:
            text: 'Back to menu'
            on_press: root.manager.current = 'menu'